// id用获取唯一id的方法设置
$.groupData = [{
    "className": "css案例",
    "list": [{
        "id": "id-0-0",
        "title": "animate.css动画框架",
        "url": "animate.html"
    }, {
        "id": "id-0-1",
        "title": "flex骰子布局",
        "url": "flex骰子布局.html"
    }, {
        "id": "id-0-2",
        "title": "导航链接小三角,导航border动画效果,导航弹层动画效果",
        "url": "css小技巧.html"
    }, {
        "id": "id-0-3",
        "title": "css正三角形+矩形移动动画",
        "url": "css正三角形+矩形移动动画.html"
    }, {
        "id": "id-0-4",
        "title": "flex布局",
        "url": "flex布局.html"
    }, {
        "id": "id-0-5",
        "title": "使用绝对定位让整个页面不滚动-局部可以滚动(vue-elema)",
        "url": "使用绝对定位让整个页面不滚动-局部可以滚动.html"
    }, {
        "id": "id-0-6",
        "title": "1px移动端",
        "url": "1px移动端.html"
    }, {
        "id": "id-0-8",
        "title": "css各种图形合集",
        "url": "css各种图形合集.html"
    }, {
        "id": "id-0-9",
        "title": "css常用布局.",
        "url": "css常用布局.html"
    }, {
        "id": "id-0-7",
        "title": "上传功能自定义样式",
        "url": "上传自定义样式.html"
    }]
}, {
    "className": "js案例",
    "list": [{
        "id": "id-1-66",
        "title": "聊天插件",
        "url": "chat/index.html",
        "external": true
    },{
        "id": "id-1-3",
        "title": "移动端tab切换_zepto",
        "url": "移动端tab切换_zepto.html",
        "external": true
    }, {
        "id": "id-1-4",
        "title": "PC端tab切换_Jquery",
        "url": "PC端tab切换.html"
    }, {
        "id": "id-1-5",
        "title": "惰性加载案例",
        "url": "惰性加载案例.html"
    }, {
        "id": "id-1-111",
        "title": "jquery三级联动插件",
        "url": "jquery三级联动插件.html"
    }, {
        "id": "id-1-6",
        "title": "获取上传文件路径和预览图片",
        "url": "获取上传文件路径和预览图片.html"
    }, {
        "id": "id-1-8",
        "title": "一维数组转树形json",
        "url": "一维数组转树形json.html"
    }, {
        "id": "id-1-9",
        "title": "预览图片和html2canvas插件生成元素内容的图片",
        "url": "预览图片和canvas画图.html",
        "external": true
    }, {
        "id": "id-1-10",
        "title": "右键菜单",
        "url": "右键菜单.html"
    }, {
        "id": "id-1-12",
        "title": "微信网页悬浮窗",
        "url": "微信网页悬浮窗.html",
        "external": true
    }, {
        "id": "id-1-13",
        "title": "基于HTML5的drag_drop的模块拖动插入排序和删除",
        "url": "基于HTML5的drag_drop的模块拖动插入排序和删除.html",
    }, {
        "id": "id-1-14",
        "title": "点击页面出现文字动画效果",
        "url": "点击页面出现文字动画效果.html",
    }, {
        "id": "id-1-15",
        "title": "动画的缓动算法",
        "url": "动画的缓动算法.html",
        "external":true
    }, {
        "id": "id-1-15",
        "title": "移动设备上任意元素在屏幕内惯性弹动",
        "url": "移动设备上任意元素在屏幕内惯性弹动.html",
        "external":true
    }, {
        "id": "id-1-16",
        "title": "PC子元素scroll父元素容器不跟随滚",
        "url": "PC子元素scroll父元素容器不跟随滚.html",
        "external":true
    }, {
        "id": "id-1-11",
        "title": "重复选择select的某一项再次触发change事件方法",
        "url": "重复选择select的某一项再次触发change事件方法.html"
    }]
}, {
    "className": "知识点",
    "list": [{
            "id": "id-2-00",
            "title": "纯文字",
            "url": "纯文字.html"
        }, {
            "id": "id-2-0",
            "title": "事件委托",
            "url": "事件委托.html"
        }, {
            "id": "id-2-2",
            "title": "js通过原型链继承",
            "url": "js继承.html"
        }, {
            "id": "id-2-3",
            "title": "js闭包",
            "url": "js闭包.html"
        }, {
            "id": "id-2-4",
            "title": "用ES5模拟实现ES6中的Map类",
            "url": "用ES5模拟实现ES6中的Map类.html"
        }, {
            "id": "id-2-5",
            "title": "键盘事件总结",
            "url": "键盘事件总结.html"
        }, {
            "id": "id-2-6",
            "title": "键盘事件只在局部元素有效",
            "url": "键盘事件只在局部元素有效.html"
        }, {
            "id": "id-2-7",
            "title": "浏览器鼠标_键盘_htm事件.html",
            "url": "浏览器鼠标_键盘_htm事件.html"
        }, {
            "id": "id-2-8",
            "title": "js中的this",
            "url": "js中的this.html"
        },
        {
            "id": "id-2-10",
            "title": "防抖函数与节流函数",
            "url": "防抖函数与节流函数.html"
        },
        {
            "id": "id-2-9",
            "title": "js开发技巧",
            "url": "js开发技巧.html"
        }
    ]
}, {
    "className": "移动端",
    "list": [{
        "id": "id-3-0",
        "title": "移动端touchmouve做刮奖效果",
        "url": "刮奖.html",
        "external": true
    }, {
        "id": "id-3-1",
        "title": "移动端登陆",
        "url": "h5/login.html",
        "external": true
    }, {
        "id": "id-3-2",
        "title": "移动端个人主页",
        "url": "h5/personHome.html",
        "external": true
    }]
}, {
    "className": "common",
    "list": [{
        "id": "id-4-0",
        "title": "md5密码加密",
        "url": "md5.html"
    }, {
        "id": "id-4-3",
        "title": "递归与异步请求",
        "url": "递归与异步请求.html"
    }, {
        "id": "id-4-5",
        "title": "localforage使用案例",
        "url": "localforage使用案例.html",
        "external": true
    }, {
        "id": "id-4-6",
        "title": "表单控制",
        "url": "表单控制.html",
    }, {
        "id": "id-4-4",
        "title": "递归与异步请求_bootrapDialog",
        "url": "递归与异步请求_bootrapDialog.html"
    }]
}, {
    "className": "bootstrap",
    "list": [{
        "id": "id-6-0",
        "title": "远程加载模态框内容",
        "url": "远程加载模态框内容.html"
    }]
}, {
    "className": "数据库知识",
    "list": [{
        "id": "id-7-0",
        "title": "数据字典或码表设计",
        "url": "数据字典或码表设计.html"
    }]
}, {
    "className": "websocket和webworker",
    "list": [{
        "id": "id-8-1",
        "title": "websocket",
        "url": "websocket.html"
    }]
}, {
    "className": "jQuery",
    "list": [{
        "id": "id-9-1",
        "title": "jquery事件命名空间用法",
        "url": "jquery事件命名空间用法.html"
    },{
        "id": "id-9-2",
        "title": "jquery插件的良好写法",
        "url": "jquery插件的良好写法.html"
    }]
}]